export enum CommonErrorStatus {
    DATABASE_ACCESS_ERROR = "DATABASE_ACCESS_ERROR",
    NETWORK_ERROR = "NETWORK_ERROR",
    UNKNOWN_ERROR = "UNKNOWN_ERROR",
    UNREACHABLE_ERROR = "UNREACHABLE_ERROR"
}